apiVersion: apps/v1
kind: ReplicaSet
metadata:
   name: mpapp-rs
   labels:
     app: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: mvmc/myapp01
          ports:
            - containerPort: 80

